name: TestAndBuild

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  TestAndBuild:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn
      - run: yarn test
      - run: yarn build